[[FlangClassic]]
arch = "x86_64"
git-tree-sha1 = "0b0d9b75e4583ced1cdfff9325f79d14601cc371"
libc = "musl"
os = "linux"

    [[FlangClassic.download]]
    sha256 = "b531b0aad9c41283aeb0933c7d7bd114b3a48a1d5272fd0b11f8a8073dce739a"
    url = "https://github.com/JuliaBinaryWrappers/FlangClassic_jll.jl/releases/download/FlangClassic-v13.0.0+1/FlangClassic.v13.0.0.x86_64-linux-musl.tar.gz"
