# Autogenerated wrapper script for FlangClassic_jll for x86_64-linux-musl
export flang, flang1, flang2

JLLWrappers.@generate_wrapper_header("FlangClassic")
JLLWrappers.@declare_executable_product(flang)
JLLWrappers.@declare_executable_product(flang1)
JLLWrappers.@declare_executable_product(flang2)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        flang,
        "bin/flang",
    )

    JLLWrappers.@init_executable_product(
        flang1,
        "bin/flang1",
    )

    JLLWrappers.@init_executable_product(
        flang2,
        "bin/flang2",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
